# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_cross_pseudo_supervision.py --root_path ../data/ACDC --exp ACDC/CPS --batch_size 16 --num_classes 4 --max_iterations 30000 --base_lr 0.03 --labeled_ratio 10 --cross_val 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_cross_pseudo_supervision.py --root_path ../data/ACDC --exp ACDC/CPS --batch_size 16 --num_classes 4 --max_iterations 30000 --base_lr 0.03 --labeled_ratio 20 --cross_val 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_cross_pseudo_supervision.py --root_path ../data/ACDC --exp ACDC/CPS --batch_size 16 --num_classes 4 --max_iterations 30000 --base_lr 0.03 --labeled_ratio 40 --cross_val 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 30000 --base_lr 0.03 --labeled_ratio 10 --cross_val 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 30000 --base_lr 0.03 --labeled_ratio 20 --cross_val 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 30000 --base_lr 0.03 --labeled_ratio 40 --cross_val 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fixmatch.py --root_path ../data/ACDC --exp ACDC/FixMatch --batch_size 16 --num_classes 4 --max_iterations 30000 --base_lr 0.03 --labeled_ratio 10 --cross_val 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fixmatch.py --root_path ../data/ACDC --exp ACDC/FixMatch --batch_size 16 --num_classes 4 --max_iterations 30000 --base_lr 0.03 --labeled_ratio 20 --cross_val 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fixmatch.py --root_path ../data/ACDC --exp ACDC/FixMatch --batch_size 16 --num_classes 4 --max_iterations 30000 --base_lr 0.03 --labeled_ratio 40 --cross_val 0
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 30000 --base_lr 0.03 --labeled_ratio 1 --cross_val 0 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fixmatch.py --root_path ../data/ACDC --exp ACDC/FixMatch --batch_size 16 --num_classes 4 --max_iterations 30000 --base_lr 0.03 --labeled_ratio 20 --cross_val 0 