srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_interpolation_consistency_training.py --root_path ../data/ACDC --exp ACDC/ICT --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 1 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_interpolation_consistency_training.py --root_path ../data/ACDC --exp ACDC/ICT --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 2 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_interpolation_consistency_training.py --root_path ../data/ACDC --exp ACDC/ICT --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 3 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_interpolation_consistency_training.py --root_path ../data/ACDC --exp ACDC/ICT --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 4 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_interpolation_consistency_training.py --root_path ../data/ACDC --exp ACDC/ICT --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 0 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_interpolation_consistency_training.py --root_path ../data/ACDC --exp ACDC/ICT --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 1 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_interpolation_consistency_training.py --root_path ../data/ACDC --exp ACDC/ICT --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 2 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_interpolation_consistency_training.py --root_path ../data/ACDC --exp ACDC/ICT --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 3 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_interpolation_consistency_training.py --root_path ../data/ACDC --exp ACDC/ICT --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 4 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_interpolation_consistency_training.py --root_path ../data/ACDC --exp ACDC/ICT --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 0