# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 1 --fold 1 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 1 --fold 2 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 1 --fold 3 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 1 --fold 4 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 1 --fold 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 2 --fold 1 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 2 --fold 2 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 2 --fold 3 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 2 --fold 4 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 2 --fold 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 4 --fold 1 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 4 --fold 2 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 4 --fold 3 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 4 --fold 4 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 4 --fold 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 1 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 2 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 3 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 4 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 1 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 2 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 3 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 4 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ACDC --exp ACDC/FullSup --batch_size 16 --num_classes 4 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 1 --fold 1 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 1 --fold 2 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 1 --fold 3 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 1 --fold 4 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 1 --fold 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 2 --fold 1 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 2 --fold 2 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 2 --fold 3 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 2 --fold 4 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 2 --fold 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 4 --fold 1 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 4 --fold 2 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 4 --fold 3 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 4 --fold 4 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 4 --fold 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 1 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 2 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 3 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 4 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 1 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 2 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 3 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 4 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/ProstateX --exp ProstateX/FullSup --batch_size 16 --num_classes 3 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 1 --fold 1 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 1 --fold 2 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 1 --fold 3 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 1 --fold 4 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 1 --fold 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 2 --fold 1 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 2 --fold 2 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 2 --fold 3 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 2 --fold 4 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 2 --fold 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 4 --fold 1 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 4 --fold 2 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 4 --fold 3 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 4 --fold 4 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 4 --fold 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 1 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 2 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 3 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 4 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 8 --fold 0 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 1 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 2 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 3 &
# srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 4 &
srun -p MIA -n 1 -c 4 --mpi=pmi2 --gres=gpu:1 python -u train_fully_supervised.py --root_path ../data/CHAOS --exp CHAOS/FullSup --batch_size 16 --num_classes 5 --max_iterations 60000 --base_lr 0.03 --labeled_ratio 16 --fold 0